baseURL = 'https://aelathil.github.io'
languageCode = 'it-it'
title = 'Tutorato 2023-2024, I semestre'
theme = 'hugo-theme-texify'

paginate = 5                              # number of posts each page

[author]
email = "" # your email
name = ""          # your name

# https://gohugo.io/getting-started/configuration-markup
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.renderer]
unsafe = false # enable html in markdown
[markup.highlight]
style = "monokai" # syntax highlight style, see https://xyproto.github.io/splash/docs/

# https://gohugo.io/content-management/menus/
[[menu.main]]
identifier = "home" # section id
name = "Home"       # section display title
url = "/"           # path to the section
weight = 1          # order of sections
[[menu.main]]
identifier = "aritmetica"
name = "Aritmetica"
url = "/aritmetica/"
weight = 2
[[menu.main]]
identifier = "analisi"
name = "Analisi"
url = "/analisi/"
weight = 3

########################
# TEXIFY THEME OPTIONS #
########################

[params]
description = "an example site for hugo theme TeXify" # website description
favicon = "favicon.ico" # path to website icon, relative to ./static
footnote = """
Follow me on <a class=link href=https://github.com/queensferryme>GitHub</a>,
<a class=link href=https://twitter.com/queensferryme>Twitter</a> or
<a class=link href=/index.xml>RSS</a> |
<a class=link href=https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh target=_blank rel=noopener>CC BY-NC-SA 4.0</a>
""" # notes in the website footer
keywords = ["hugo", "latex", "theme"] # website keywords

customCSS = []            # path to custom css files, relative to ./static
customJS = []             # path to custom js files, relative to ./static
dateFormat = "2006-01-02" # date format, see https://gohugo.io/functions/format/
fullTextRSS = true        # output full-text (instead of only summary) rss
emphasisWithDots = true   # use dots to emphasize chinese texts, see https://zh.wikipedia.org/wiki/%E7%9D%80%E9%87%8D%E5%8F%B7
since = "2019"            # website created year
toc = false               # whether to enable table of contents in posts

[params.math]
enable = true # whether to enable math typesetting
use = "katex"  # katex or mathjax

[params.outdated]
enable = false # whether to display warnings for outdated posts
limit = 1000   # days between last modified time and outdated time
# warning to be displayed
warning = "⚠️ It has been <i>%d</i> days since the last update, the content of the article may be outdated."

# https://utteranc.es
[params.utterances]
enable = false # whether to enable utterances
# paste utterances' <script></script> configuration between the triple quotes
script = """
"""

